# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black

-   repo: https://github.com/sqlalchemyorg/zimports
    rev: v0.6.0
    hooks:
    -   id: zimports

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-import-order
          - flake8-builtins
          - flake8-future-annotations>=0.0.5
          - flake8-docstrings>=1.6.0
          - flake8-rst-docstrings
          # flake8-rst-docstrings dependency, leaving it here
          # in case it requires a version pin
          - pydocstyle
          - pygments

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
        # Misc linters
      - id: check-yaml
      - id: check-toml
        # Simple cleanliness things
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=500]

# This is disabled by default
# Run it manually with `pre-commit run --hook-stage manual`
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        stages: [manual]
        args: ["--line-length", "79"]
        additional_dependencies: [black==22.3.0]

# Basic RST validator
-   repo: https://github.com/myint/rstcheck
    rev: v6.0.0
    hooks:
      - id: rstcheck
        stages: [manual]
